### ISSUE TITLE
Convert self-certification questionnaire to Markdown

### ISSUE THREAD

**Issue by stephenkilbaneadi** [OpenChain-Project/Reference-Material#18]
Here is our self-certification questionnaire: https://github.com/OpenChain-Project/Reference-Material/blob/master/Self-Certification-Questionnaire/Official/2.1/en/OpenChain%20Self-Certification%20Questionnaire%202021-11-26.docx

**Comment by stephenkilbaneadi** [comment]
PR #25  addresses this

**Comment by shanecoughlan** [comment]
Awesome!
