### ISSUE TITLE
Convert merger-and-acquisition-using-OpenChain guide to Markdown

### ISSUE THREAD

**Issue by stephenkilbaneadi** [OpenChain-Project/Reference-Material#20]
Here is a document about using OpenChain in Mergers and Acquisitions: https://github.com/OpenChain-Project/Reference-Material/blob/master/Guides/Official/OpenChain-in-Mergers-and-Acquisitions/2.0/en/Assessment-Of-OS-Practices-In-Merger-and-Acquisition.docx

**Comment by kappapiana** [comment]
Issue is being addressed by #31
