### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by stephenkilbaneadi** [OpenChain-Project/Reference-Material#22]
Create a file that provides advice on how to submit contributions to the repo, as per best practice, e.g. https://patterns.innersourcecommons.org/p/base-documentation

**Comment by stephenkilbaneadi** [comment]
I have a draft for this, but I have a couple of other PRs ahead of this one. I can plausibly rearrange things to make this parallel, though.

**Comment by shanecoughlan** [comment]
To align with project charter, we should require all submissions are CC-0 except for Case Studies, CC-BY-SA.

**Comment by shanecoughlan** [comment]
"Case Studies may be CC-BY-SA or less restrictive."
