### ISSUE TITLE
Small company playbook links not working

### ISSUE THREAD

**Issue by anajsana** [OpenChain-Project/Reference-Material#26]
I've noticed the links from the new [playbook for small companies](https://www.openchainproject.org/featured/2022/10/04/small-company-playbook-v1) are not working, at least in the PDF doc 🙂 Is it possible to get this fixed?

![Screenshot 2022-10-05 at 09-54-18 Microsoft Word - OpenChain PlayBook - Small Company docx - OpenChain PlayBook - Small Company pdf](https://user-images.githubusercontent.com/43671777/194009195-9c6ec053-9017-493c-8c52-3152f8675031.png)

**Comment by shanecoughlan** [comment]
Hi @anajsana! I see an issue with the links not working in the GitHub preview, but the downloaded document works fine. Can you confirm that your issue is related to the GitHub preview of the PDF as opposed to the downloaded copy of the document?

**Comment by anajsana** [comment]
Hello @shanecoughlan ! The downloaded PDF has some links working, but some of them do not, specifically, those ones within the "Executing Our Plan" Section

**Comment by shanecoughlan** [comment]
Thanks Ana! Great catch. The PDF issue is related to print-ready accessibility. To fix this, the links have been moved into footnotes, and we are good to go.
