### ISSUE TITLE
[Bug] Markdown errors in Self-Certification/Questionnaire

### ISSUE THREAD

**Issue by lucasgonze** [OpenChain-Project/Reference-Material#35]
## **Describe the bug**

The [Self-Certification/Questionnaire](https://github.com/OpenChain-Project/Reference-Material/blob/master/Self-Certification/Questionnaire/ISO5230-2020/en/OpenChain%20Self-Certification%20Questionnaire%202021-11-26.md) has markdown errors in the external links. The links appear to work but the text is showing markdown syntax instead of human-friendly words.

## **Screenshots**

Error as rendered by the markdown interpreter:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/111581/196735166-6d64bc21-b36c-4d32-b954-e20f3da8ac00.png">

Source code of one of the errors:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/111581/196735062-c16db496-ea9e-4b33-b200-79af5810ec05.png">

**Comment by lucasgonze** [comment]
Fixed

**Comment by shanecoughlan** [comment]
@lucasgonze I see this was addressed in Pull Request 36, which is pending review.

@goneall flagged for your attention.
