### ISSUE TITLE
[Improvement] Supplier Leaflet: Steve - This seems very long, overall. I think there's scope for something much shorter and punchier.

### ISSUE THREAD

**Issue by shanecoughlan** [OpenChain-Project/Reference-Material#65]
This seems very long, overall. I think there's scope for something much shorter and punchier.

**Comment by shanecoughlan** [comment]
Leaflet: https://github.com/OpenChain-Project/Reference-Material/blob/master/Education-For-Suppliers/Supplier-Education-Leaflet/supply-chain-education-leaflet-version-2-2024/supply-chain-education-leaflet-version-2_en.md

**Comment by jacobdjwilson** [comment]
I have added a table of contents ahead of the Introduction section similar to the original PDF leaflet. In addition I slightly modified two headings to be more succinct.

OLD: What you need to do to receive the benefits of open source
NEW: Receiving the benefits of open source

OLD: Open source information required to be delivered with software
NEW: Delivery of open source software

[PR 70](https://github.com/OpenChain-Project/Reference-Material/pull/70)

**Comment by shanecoughlan** [comment]
Fixed here by @jacobdjwilson
