### ISSUE TITLE
[Improvement] supply-chain-education-leaflet-version-2_en.md question/improvement

### ISSUE THREAD

**Issue by winterrocks** [OpenChain-Project/Reference-Material#83]
## **Describe the improvement**
https://github.com/OpenChain-Project/Reference-Material/blob/master/Education-For-Suppliers/Supplier-Education-Leaflet/supply-chain-education-leaflet-version-2-2024/supply-chain-education-leaflet-version-2_en.md states under heading [Let’s learn the basics of open source](https://github.com/OpenChain-Project/Reference-Material/blob/master/Education-For-Suppliers/Supplier-Education-Leaflet/supply-chain-education-leaflet-version-2-2024/supply-chain-education-leaflet-version-2_en.md#lets-learn-the-basics-of-open-source):
> When an item with open source software is delivered to another party, information related to all the included open source must be provided.

This IMHO is not 100% correct because if the **another party** is within the same legal entity there is no **must** to provide the information related to the included open source. Of course, it is good if this information is delivered even within the same legal entity, but there could be e.g., an internal tool that is delivered from the developer team to the internal user within the same legal entity. 

**Ideas for the sentence**
1. When an item with open source software is delivered to another **external** party, information related to all the included open source must be provided.
2. When an item with open source software is delivered to another **legal entity**, information related to all the included open source must be provided.

**Additional sentence**
But it would be good to deliver the information related to all the included open source even when distributing withing the same organization.

**Comment by shanecoughlan** [comment]
Adjusted to the following to incorporate your suggestions:

In general, when an item that includes open source software is delivered to another company or legal entity, information related to all the included open source should be provided. It is good practice to deliver this type of information even when distributing internally to ensure accurate record-keeping.
